<!-- This file was generated by the SimpleWebFront-DBDesigner4-Plugin. See http://www.fabforce.net -->
<?php


// Copyright (C) 2003 Bayer Ulrich, Michael Zinner

//

// This file is free software; you can redistribute it and/or modify

// it under the terms of the GNU General Public License as published by

// the Free Software Foundation; either version 2 of the License, or

// (at your option) any later version.

//

// This file is distributed in the hope that it will be useful,

// but WITHOUT ANY WARRANTY; without even the implied warranty of

// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

// GNU General Public License for more details.



// You should have received a copy of the GNU General Public License

// along with DBDesigner4; if not, write to the Free Software

// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

//

//----------------------------------------------------------------------------











?>



<?php  $heading = "dvdrental"; ?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"

            "http://www.w3.org/TR/html4/loose.dtd">

<html>

<head>

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">

    <meta http-equiv="Content-Script-Type" content="text/javascript">

    <meta http-equiv="Content-Style-Type" content="text/css">

    <meta name="robots" content="noindex">

    <link rel="StyleSheet" href="incs/document.css" type="text/css" media="screen">

    <title><?php echo $heading ?></title>

</head>



<body>



<?php



    //an array of the form (array ("Gruppe1.View1" => "test.png")..

    $imageNames = array ( "all.public.actor"=>"icons_01.png","all.public.actor_info"=>"icons_01.png","all.public.address"=>"icons_01.png","all.public.category"=>"icons_01.png","all.public.city"=>"icons_01.png","all.public.country"=>"icons_01.png","all.public.customer"=>"icons_01.png","all.public.customer_list"=>"icons_01.png","all.public.film"=>"icons_01.png","all.public.film_actor"=>"icons_01.png","all.public.film_category"=>"icons_01.png","all.public.film_list"=>"icons_01.png","all.public.inventory"=>"icons_01.png","all.public.language"=>"icons_01.png","all.public.nicer_but_slower_film_list"=>"icons_01.png","all.public.payment"=>"icons_01.png","all.public.rental"=>"icons_01.png","all.public.sales_by_film_category"=>"icons_01.png","all.public.sales_by_store"=>"icons_01.png","all.public.staff"=>"icons_01.png","all.public.staff_list"=>"icons_01.png","all.public.store"=>"icons_01.png");



    function println($str)

    {

        print $str;

        print "\n";

    }

    

    function displayGroup ($groupName, $views)

    { 

        global $imageNames;

               

		print '

<!-- group start -->

<table border="0" cellpadding="0" cellspacing="0">

<!-- group header -->

  <tr>

    <td colspan="3">

      <table border="0" cellpadding="0" cellspacing="0">

        <tr>

          <td nowrap><img src="images/1ptrans.png" width="8" height="1"><img src="images/group_header_l.png"></td>

          <td background="images/group_header_m.png"><font class="fontS">'.$groupName.'</font></td>

          <td><img src="images/group_header_r.png"></td>

        </tr>

      </table></td>

  </tr>

<!-- group main -->

  <tr>

    <td width="10"><img src="images/group_lt.png" width="10"></td>

    <td background="images/group_t.png"><img src="images/1ptrans.png" height="9"></td>

    <td width="11"><img src="images/group_rt.png" width="11"></td>

  </tr>

  <tr>

    <td height="100%" background="images/group_l.png"><img src="images/1ptrans.png" width="10"></td>

    <td bgcolor="#f6f6f6">

<!-- group icons -->

      <table border="0" cellpadding="0" cellspacing="0">

        <tr>';

foreach ($views as $viewName => $linkTarget) {

print '          <td align="center"><a href="'.$linkTarget.'"><img src="images/icons/'.$imageNames["$groupName.$viewName"].'" border="0"></a></td>

          <td><img src="images/1ptrans.png" width="10"></td>'; }

print '        </tr>

        <tr>';

foreach ($views as $viewName => $linkTarget) {

print '          <td align="center"><a href="'.$linkTarget.'">'.$viewName.'</td>

          <td>&nbsp;</td>'; }

print '        </tr>

      </table>

    </td>

    <td background="images/group_r.png"><img src="images/1ptrans.png" width="11"></td>

  </tr>

  <tr>

    <td width="10"><img src="images/group_lb.png" width="10"></td>

    <td background="images/group_b.png"><img src="images/1ptrans.png" height="10"></td>

    <td width="11"><img src="images/group_rb.png" width="11"></td>

  </tr>

</table>

<!-- group end -->';        

    }

?>

<br>

<table width="100%" height="37" border="0" cellpadding="0" cellspacing="0" background="images/headerbg.png">

  <td background align="center" class="fontBig"><?php echo $heading ?></td>

</table>

<br>



<table border="0" cellpadding="0" cellspacing="0">

<tr><td><img src="images/1ptrans.png" width="10"></td><td>


<table border="0"><tr><td><?php displayGroup("all",array( "public.actor"=>"all_public.actor_frame.php?page=0&mode=normal","public.actor_info"=>"all_public.actor_info_frame.php?page=0&mode=normal","public.address"=>"all_public.address_frame.php?page=0&mode=normal","public.category"=>"all_public.category_frame.php?page=0&mode=normal","public.city"=>"all_public.city_frame.php?page=0&mode=normal","public.country"=>"all_public.country_frame.php?page=0&mode=normal","public.customer"=>"all_public.customer_frame.php?page=0&mode=normal","public.customer_list"=>"all_public.customer_list_frame.php?page=0&mode=normal","public.film"=>"all_public.film_frame.php?page=0&mode=normal","public.film_actor"=>"all_public.film_actor_frame.php?page=0&mode=normal","public.film_category"=>"all_public.film_category_frame.php?page=0&mode=normal","public.film_list"=>"all_public.film_list_frame.php?page=0&mode=normal","public.inventory"=>"all_public.inventory_frame.php?page=0&mode=normal","public.language"=>"all_public.language_frame.php?page=0&mode=normal","public.nicer_but_slower_film_list"=>"all_public.nicer_but_slower_film_list_frame.php?page=0&mode=normal","public.payment"=>"all_public.payment_frame.php?page=0&mode=normal","public.rental"=>"all_public.rental_frame.php?page=0&mode=normal","public.sales_by_film_category"=>"all_public.sales_by_film_category_frame.php?page=0&mode=normal","public.sales_by_store"=>"all_public.sales_by_store_frame.php?page=0&mode=normal","public.staff"=>"all_public.staff_frame.php?page=0&mode=normal","public.staff_list"=>"all_public.staff_list_frame.php?page=0&mode=normal","public.store"=>"all_public.store_frame.php?page=0&mode=normal") ); ?></td></tr></table>

</td></tr>

</table>



</body>

</html>
